const Path = {
    login : "./login",
    signup : "./signup",
    forgotPassword : "./forgot-password",
    resetPassword : "./reset-password",
    changePassword : "./change-password",
    home : "/",
    homePage : "/",
    dashboard: "/",
    userManagement: "user-management",
    productManagement: "product-management",
    orderManagement: "order-management",
    totalOrders : "/total-orders",
    totalDelivered : "/total-delivered",
    totalCancelled : "/total-cancelled",
    totalRevenue : "/total-revenue",
    customer : "/customer",
    customerDetails : "customer-details",
    chef : "/chef",
    chefDetails : "/chef-details",
    chefFood : "/chef-food-details",
    allItems : "/all-items",
    editItems : "/edit-items",
    categories : "/product-categories",
    addCategory : "/add-category",
    tags : "/tags",
    addTag : "/add-tags",
    orders : "/orders",
    orderManage : "/order-management"
};

export default Path